services:
  web:
    build: ./web
    container_name: zigbee_lab_web
    ports:
      - "8090:8080"
    # depends_on:
    #   - mqtt
    environment:
      MQTT_HOST: core-mosquitto
      MQTT_PORT: "1883"
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_SET_TOPIC: zigbee2mqtt/0xa4c1387f4dcc1553/set
      MQTT_STATE_TOPIC: zigbee2mqtt/0xa4c1387f4dcc1553
      MQTT_BUTTON_TOPIC: ${MQTT_BUTTON_TOPIC}
      GIT_REPO_URL: https://github.com/LuisAlbertoFP/zigbee2mqtt.git
    restart: unless-stopped
    networks:
      - default
      - hassio
    volumes:
      - web_cache:/opt/cache

networks:
  hassio:
    external: true
    name: hassio