services:
  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: koenkk/zigbee2mqtt
  #   restart: unless-stopped
  #   volumes:
  #     - ./data:/app/data
  #     - /run/udev:/run/udev:ro
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0
  #   ports:
  #     - "9090:8080"
  #   environment:
  #     - TZ=Europe/Madrid

  # mqtt:
  #   container_name: mqtt
  #   image: eclipse-mosquitto:2.0
  #   restart: unless-stopped
  #   volumes:
  #     - ./mosquitto:/mosquitto
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #   command: "mosquitto -c /mosquitto/mosquitto-no-auth.conf"

  # esphome:
  #   container_name: esphome
  #   image: ghcr.io/esphome/esphome:latest
  #   restart: unless-stopped
  #   ports:
  #     - "6052:6052"
  #   volumes:
  #     - ./esphome:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TZ=Europe/Madrid



  web:
    build: ./web
    container_name: zigbee_lab_web
    ports:
      - "8090:8080"
    # depends_on:
    #   - mqtt
    environment:
      #MQTT_HOST: mqtt
      MQTT_HOST: core-mosquitto
      MQTT_PORT: "1883"
      MQTT_USERNAME: webui
      MQTT_PASSWORD: cambia_webui
      MQTT_SET_TOPIC: zigbee2mqtt/0xa4c1387f4dcc1553/set
      MQTT_STATE_TOPIC: zigbee2mqtt/0xa4c1387f4dcc1553
    restart: unless-stopped
 #   volumes:
 #     - ./web:/app 

  # simulator:
  #   build: ./simulador
  #   container_name: zigbee_lab_simulator
  #   depends_on:
  #     - mqtt
  #   environment:
  #     MQTT_HOST: mqtt
  #     MQTT_PORT: "1883"
  #     MQTT_SET_TOPIC: zigbee2mqtt/lab_ts0001_switch/set
  #     MQTT_STATE_TOPIC: zigbee2mqtt/lab_ts0001_switch
  #     IEEE_ADDRESS: "0xa4c1387f4dcc1553"
  #     MODEL: "TS0001_switch_module"
  #     FRIENDLY_NAME: "lab_ts0001_switch"

  # admin_web:
  #   build: ./admin_web
  #   container_name: mqtt_admin_web
  #   restart: unless-stopped
  #   ports:
  #     - "8091:8080"
  #   depends_on:
  #     - mqtt
  #   environment:
  #     MQTT_HOST: mqtt
  #     MQTT_PORT: "1883"
  #     MQTT_ADMIN_USER: admin
  #     MQTT_ADMIN_PASS: cambia_esto
  #     MQTT_WEB_USER: webui
  #     MQTT_WEB_PASS: cambia_webui
  #     MQTT_WEB_ROLE: webui_role
  #     MQTT_TOPIC_SET: zigbee2mqtt/lab_ts0001_switch/set
  #     MQTT_TOPIC_STATE: zigbee2mqtt/lab_ts0001_switch
  #   volumes:
  #     - ./admin_web:/app

  mqtt-admin:
    container_name: mqtt-admin
    build: ./mqtt-admin
    restart: unless-stopped
    ports:
      - "9096:8080"
    volumes:
      - ./mqtt-admin:/app 
      - ./mosquitto:/mosquitto
      - /var/run/docker.sock:/var/run/docker.sock