FROM python:3.12-slim

WORKDIR /app

RUN apt update && apt install -y docker.io

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPY app.py .
#COPY templates ./templates

EXPOSE 8080

CMD ["python", "app.py"]